#!/bin/bash

if [ "$#" -ne 2 ]; then
	echo "Usage: mkalias <alias_name> <command>"
	exit 1
fi

ALIAS_NAME=$1
COMMAND=$2

NEW_ALIAS="alias $ALIAS_NAME=\"$COMMAND\""

echo "Is the following alias correct? (y/n)"
echo $NEW_ALIAS

read response

if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]
then
	echo "Appending new alias to .zshrc..."
	echo $NEW_ALIAS >> ~/.zshrc
	echo "Alias added succesfully."
else
	echo "Aborted."
fi	

source ~/.zshrc
echo "##########################"
echo "The last entries in ~/.zshrc are:"
tail -n 5 ~/.zshrc
